# Generated by Django 6.0.6 on 2026-08-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mfa'),
        ('accounts', '0006_refreshtokensession'),
    ]

    operations = [
    ]
