# Generated by Django 6.0.6 on 2026-08-03 08:52

import hashlib
import json

from django.db import migrations, models


def backfill_integrity_hashes(apps, schema_editor):
    AuditEvent = apps.get_model("audit", "AuditEvent")
    tenant_ids = AuditEvent.objects.order_by().values_list("tenant_id", flat=True).distinct()
    for tenant_id in tenant_ids:
        previous_hash = ""
        events = AuditEvent.objects.filter(tenant_id=tenant_id).order_by("id")
        for event in events:
            payload = {
                "tenant_id": event.tenant_id,
                "actor_type": event.actor_type,
                "actor_id": event.actor_id,
                "action": event.action,
                "target_type": event.target_type,
                "target_id": event.target_id,
                "ip_address": event.ip_address,
                "user_agent": event.user_agent,
                "device_fingerprint": event.device_fingerprint,
                "metadata_json": event.metadata_json,
                "sensitive_metadata_hash": event.sensitive_metadata_hash,
                "previous_event_hash": previous_hash,
                "created_at": event.created_at.isoformat(),
            }
            integrity_hash = hashlib.sha256(
                json.dumps(payload, sort_keys=True, default=str, separators=(",", ":")).encode()
            ).hexdigest()
            AuditEvent.objects.filter(pk=event.pk).update(
                previous_event_hash=previous_hash,
                integrity_hash=integrity_hash,
            )
            previous_hash = integrity_hash


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="integrity_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="previous_event_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.RunPython(backfill_integrity_hashes, migrations.RunPython.noop),
    ]
