# Generated by Django 6.0.6 on 2026-08-03 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_auditevent_integrity_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
