# Generated by Django 6.0.6 on 2026-08-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0002_alter_upload_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("uploaded", "Uploaded"),
                    ("consumed", "Consumed"),
                    ("promoted", "Promoted"),
                    ("expired", "Expired"),
                    ("deleted", "Deleted"),
                ],
                db_index=True,
                default="initiated",
                max_length=32,
            ),
        ),
    ]
