# Generated by Django 6.0.6 on 2026-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("code", models.CharField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("live", "Live"),
                            ("watch", "Watch"),
                            ("draft", "Draft"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("primary_metric", models.CharField(max_length=255)),
                ("secondary_metric", models.CharField(blank=True, max_length=255)),
                ("tertiary_metric", models.CharField(blank=True, max_length=255)),
                ("time_window", models.CharField(default="30 days", max_length=64)),
                ("owner_team", models.CharField(blank=True, max_length=120)),
                ("config_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
