# Generated by Django 6.0.6 on 2026-07-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("verifications", "0002_verificationdecision"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=120, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("biometric", "Biometric"),
                            ("identity_database", "Identity Database"),
                            ("liveness", "Liveness"),
                            ("risk", "Risk"),
                            ("notification", "Notification"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("testing", "Testing"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                ("configuration_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["provider_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProviderCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("document_ocr", "Document OCR"),
                            ("document_quality", "Document Quality"),
                            ("face_match", "Face Match"),
                            ("liveness", "Liveness"),
                            ("identity_lookup", "Identity Lookup"),
                            ("risk_check", "Risk Check"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("request_metadata_json", models.JSONField(blank=True, default=dict)),
                ("response_metadata_json", models.JSONField(blank=True, default=dict)),
                ("normalized_result_json", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=120)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_checks",
                        to="providers.provider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_checks",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_checks",
                        to="verifications.verification",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
