# Generated by Django 6.0.6 on 2026-07-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providercheck",
            name="check_type",
            field=models.CharField(
                choices=[
                    ("document_ocr", "Document OCR"),
                    ("document_classification", "Document Classification"),
                    ("document_quality", "Document Quality"),
                    ("face_match", "Face Match"),
                    ("liveness", "Liveness"),
                    ("identity_lookup", "Identity Lookup"),
                    ("risk_check", "Risk Check"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
