# Generated by Django 6.0.6 on 2026-07-06 16:44

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0002_alter_providercheck_check_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="configuration_json",
            field=common.fields.EncryptedJSONField(
                blank=True, default=dict, encryption_purpose="providers.configuration"
            ),
        ),
        migrations.AlterField(
            model_name="providercheck",
            name="normalized_result_json",
            field=common.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                encryption_purpose="providers.check.normalized_result",
            ),
        ),
        migrations.AlterField(
            model_name="providercheck",
            name="request_metadata_json",
            field=common.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                encryption_purpose="providers.check.request_metadata",
            ),
        ),
        migrations.AlterField(
            model_name="providercheck",
            name="response_metadata_json",
            field=common.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                encryption_purpose="providers.check.response_metadata",
            ),
        ),
    ]
