# Generated by Django 6.0.8 on 2026-08-09 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0005_providercheck_duration_ms"),
        ("tenants", "0003_alter_tenant_settings_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("route_key", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=255)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "environment",
                    models.CharField(
                        choices=[("sandbox", "Sandbox"), ("production", "Production")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("document_ocr", "Document OCR"),
                            ("document_classification", "Document Classification"),
                            ("document_quality", "Document Quality"),
                            ("face_match", "Face Match"),
                            ("liveness", "Liveness"),
                            ("identity_lookup", "Identity Lookup"),
                            ("risk_check", "Risk Check"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("country_codes_json", models.JSONField(blank=True, default=list)),
                ("document_type_ids_json", models.JSONField(blank=True, default=list)),
                (
                    "workflow_public_ids_json",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_routes",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "tenant_id",
                    "environment",
                    "capability",
                    "priority",
                    "route_key",
                    "-version",
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderRouteStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="route_steps",
                        to="providers.provider",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="providers.providerroute",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="providerroute",
            index=models.Index(
                fields=["tenant", "environment", "capability", "status"],
                name="provider_route_resolve_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerroute",
            constraint=models.UniqueConstraint(
                fields=("tenant", "route_key", "environment", "version"),
                name="provider_route_scope_version_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerroutestep",
            constraint=models.UniqueConstraint(
                fields=("route", "position"), name="provider_route_step_position_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerroutestep",
            constraint=models.UniqueConstraint(
                fields=("route", "provider"), name="provider_route_step_provider_uniq"
            ),
        ),
    ]
