# Generated by Django 6.0.8 on 2026-08-09 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0006_providerroute_providerroutestep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerroute",
            name="circuit_failure_threshold",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="providerroute",
            name="circuit_recovery_seconds",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="providerroute",
            name="final_action",
            field=models.CharField(
                choices=[
                    ("manual_review", "Manual Review"),
                    ("fail", "Fail Verification"),
                ],
                default="manual_review",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="providerroute",
            name="max_attempts_per_provider",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="providerroute",
            name="timeout_seconds",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.CreateModel(
            name="ProviderCircuitState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("closed", "Closed"),
                            ("open", "Open"),
                            ("half_open", "Half Open"),
                        ],
                        db_index=True,
                        default="closed",
                        max_length=16,
                    ),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retry_after",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "route_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circuit_state",
                        to="providers.providerroutestep",
                    ),
                ),
            ],
            options={
                "ordering": ["route_step_id"],
            },
        ),
        migrations.CreateModel(
            name="ProviderExecutionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("execution_id", models.CharField(db_index=True, max_length=64)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("provider_attempt", models.PositiveSmallIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=120)),
                ("retryable", models.BooleanField(default=False)),
                ("fallback_reason", models.CharField(blank=True, max_length=120)),
                ("timeout_seconds", models.PositiveSmallIntegerField()),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                (
                    "provider_check",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_attempt",
                        to="providers.providercheck",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_attempts",
                        to="providers.providerroute",
                    ),
                ),
                (
                    "route_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_attempts",
                        to="providers.providerroutestep",
                    ),
                ),
            ],
            options={
                "ordering": ["provider_check__verification_id", "sequence", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("execution_id", "sequence"),
                        name="provider_execution_sequence_uniq",
                    )
                ],
            },
        ),
    ]
