import json

from django.conf import settings
from django.urls import reverse

from apps.verifications.models import Verification
from common.storage import (
    build_signed_download_url,
    get_object_bytes,
    get_object_storage_evidence_bucket_name,
    put_object_bytes,
)


TERMINAL_EVIDENCE_STATUSES = {"verified", "rejected", "cancelled", "expired", "failed"}
EVIDENCE_OBJECT_ENCRYPTION_PURPOSE = "evidence.reports"


def build_verification_evidence_storage_key(verification: Verification) -> str:
    return (
        f"organizations/{verification.organization.public_id}"
        f"/verifications/{verification.public_id}"
        f"/reports/verification-report.json"
    )


def build_verification_evidence_pdf_storage_key(verification: Verification) -> str:
    return (
        f"organizations/{verification.organization.public_id}"
        f"/verifications/{verification.public_id}"
        f"/reports/verification-report.pdf"
    )


def build_verification_evidence_download_url(
    verification: Verification, request=None
) -> str | None:
    storage_key = (verification.metadata_json or {}).get("evidence_report_storage_key", "")
    if not storage_key:
        return None
    if (verification.metadata_json or {}).get("evidence_report_encrypted", False):
        url = reverse(
            "verification-evidence-report-download",
            kwargs={"verification_id": verification.public_id},
        )
        return request.build_absolute_uri(url) if request is not None else url
    bucket_name = get_object_storage_evidence_bucket_name()
    if not bucket_name:
        return None
    return build_signed_download_url(
        storage_key=storage_key,
        filename=f"{verification.public_id}-verification-report.json",
        bucket_name=bucket_name,
    )


def build_verification_evidence_pdf_download_url(
    verification: Verification, request=None
) -> str | None:
    storage_key = (verification.metadata_json or {}).get(
        "evidence_report_pdf_storage_key", ""
    )
    if not storage_key:
        return None
    if (verification.metadata_json or {}).get("evidence_report_pdf_encrypted", False):
        url = reverse(
            "verification-evidence-report-pdf-download",
            kwargs={"verification_id": verification.public_id},
        )
        return request.build_absolute_uri(url) if request is not None else url
    bucket_name = get_object_storage_evidence_bucket_name()
    if not bucket_name:
        return None
    return build_signed_download_url(
        storage_key=storage_key,
        filename=f"{verification.public_id}-verification-report.pdf",
        bucket_name=bucket_name,
    )


def _pdf_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _pdf_text(
    *,
    x: int,
    y: int,
    text: str,
    font: str = "F1",
    size: int = 11,
) -> str:
    return f"BT /{font} {size} Tf 1 0 0 1 {x} {y} Tm ({_pdf_escape(text)}) Tj ET"


def _pdf_fill_rect(*, x: int, y: int, width: int, height: int, rgb: tuple[float, float, float]) -> str:
    r, g, b = rgb
    return f"{r:.3f} {g:.3f} {b:.3f} rg {x} {y} {width} {height} re f"


def _pdf_stroke_rect(
    *, x: int, y: int, width: int, height: int, rgb: tuple[float, float, float], line_width: float = 1.0
) -> str:
    r, g, b = rgb
    return f"{line_width:.2f} w {r:.3f} {g:.3f} {b:.3f} RG {x} {y} {width} {height} re S"


def _truncate_pdf_line(value: str, limit: int = 82) -> str:
    if len(value) <= limit:
        return value
    return f"{value[: limit - 3]}..."


def render_report_pdf(*, title: str, subtitle: str, sections: list[tuple[str, list[str]]]) -> bytes:
    commands: list[str] = []
    commands.append(_pdf_fill_rect(x=0, y=720, width=612, height=72, rgb=(0.11, 0.16, 0.24)))
    commands.append(_pdf_text(x=42, y=754, text=title, font="F2", size=20))
    commands.append(_pdf_text(x=42, y=734, text=subtitle, font="F1", size=10))
    commands.append(_pdf_fill_rect(x=42, y=698, width=528, height=1, rgb=(0.82, 0.86, 0.91)))

    cursor_y = 670
    for section_title, lines in sections:
        if cursor_y < 110:
            break
        commands.append(_pdf_fill_rect(x=42, y=cursor_y - 8, width=528, height=22, rgb=(0.94, 0.96, 0.98)))
        commands.append(_pdf_text(x=50, y=cursor_y, text=section_title, font="F2", size=11))
        cursor_y -= 28
        for line in lines:
            if cursor_y < 90:
                break
            commands.append(_pdf_text(x=56, y=cursor_y, text=_truncate_pdf_line(line), font="F1", size=10))
            cursor_y -= 15
        cursor_y -= 10

    commands.append(_pdf_stroke_rect(x=36, y=36, width=540, height=740, rgb=(0.82, 0.86, 0.91), line_width=0.8))
    commands.append(_pdf_text(x=42, y=20, text="Generated by IdentityCore evidence service", font="F1", size=9))
    content_stream = "\n".join(commands).encode("latin-1", errors="replace")

    objects = [
        b"1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n",
        b"2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n",
        b"3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >> endobj\n",
        b"4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n",
        b"5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj\n",
        (
            f"6 0 obj << /Length {len(content_stream)} >> stream\n".encode("ascii")
            + content_stream
            + b"\nendstream endobj\n"
        ),
    ]

    pdf = bytearray(b"%PDF-1.4\n")
    offsets: list[int] = []
    for obj in objects:
        offsets.append(len(pdf))
        pdf.extend(obj)
    xref_offset = len(pdf)
    pdf.extend(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    pdf.extend(b"0000000000 65535 f \n")
    for offset in offsets:
        pdf.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    pdf.extend(
        (
            f"trailer << /Size {len(objects) + 1} /Root 1 0 R >>\n"
            f"startxref\n{xref_offset}\n%%EOF"
        ).encode("ascii")
    )
    return bytes(pdf)


def serialize_verification_evidence_report(verification: Verification) -> dict:
    latest_liveness = verification.liveness_checks.order_by("-checked_at").first()
    latest_face_match = verification.face_matches.order_by("-matched_at").first()
    risk_assessment = getattr(verification, "risk_assessment", None)
    decision_record = getattr(verification, "decision_record", None)
    latest_identity_document = verification.identity_documents.order_by("-created_at").first()
    document_classification = (
        (latest_identity_document.extracted_data_json or {}).get("document_classification")
        if latest_identity_document is not None
        else None
    )

    return {
        "verification_id": verification.public_id,
        "organization_id": verification.organization.public_id,
        "tenant_id": verification.tenant.public_id,
        "status": verification.status,
        "purpose": verification.purpose,
        "external_reference": verification.external_reference,
        "verification_subject": {
            "id": verification.verification_subject.public_id,
            "full_name": verification.verification_subject.full_name,
            "email": verification.verification_subject.email,
            "phone_number": verification.verification_subject.phone_number,
        },
        "identity_documents": [
            {
                "id": identity_document.public_id,
                "document_type": identity_document.document_type_id,
                "country_code": identity_document.country_profile_id,
                "status": identity_document.status,
                "extracted_data": identity_document.extracted_data_json,
            }
            for identity_document in verification.identity_documents.all()
        ],
        "document_captures": [
            {
                "id": capture.public_id,
                "side": capture.side,
                "storage_key": capture.storage_key,
                "status": capture.status,
                "quality_score": float(capture.quality_score) if capture.quality_score is not None else None,
            }
            for identity_document in verification.identity_documents.prefetch_related("captures")
            for capture in identity_document.captures.all()
        ],
        "selfie_captures": [
            {
                "id": selfie.public_id,
                "storage_key": selfie.storage_key,
                "status": selfie.status,
                "capture_type": selfie.capture_type,
            }
            for selfie in verification.selfie_captures.all()
        ],
        "checks": {
            "liveness": (
                {
                    "status": latest_liveness.status,
                    "score": float(latest_liveness.score) if latest_liveness.score is not None else None,
                    "confidence_level": latest_liveness.confidence_level,
                    "model_name": latest_liveness.model_name,
                    "model_version": latest_liveness.model_version,
                }
                if latest_liveness is not None
                else None
            ),
            "face_match": (
                {
                    "status": latest_face_match.status,
                    "match_score": (
                        float(latest_face_match.match_score)
                        if latest_face_match.match_score is not None
                        else None
                    ),
                    "confidence_level": latest_face_match.confidence_level,
                    "model_name": latest_face_match.model_name,
                    "model_version": latest_face_match.model_version,
                }
                if latest_face_match is not None
                else None
            ),
        },
        "risk_assessment": (
            {
                "id": risk_assessment.public_id,
                "risk_level": risk_assessment.risk_level,
                "risk_score": float(risk_assessment.risk_score),
                "recommendation": risk_assessment.recommendation,
            }
            if risk_assessment is not None
            else None
        ),
        "document_classification": document_classification,
        "decision": (
            {
                "id": decision_record.public_id,
                "decision": decision_record.decision,
                "decision_type": decision_record.decision_type,
                "reason_code": decision_record.reason_code,
                "reason_detail": decision_record.reason_detail,
                "decided_at": decision_record.decided_at.isoformat(),
            }
            if decision_record is not None
            else None
        ),
        "policy_snapshot": verification.policy_snapshot_json,
        "created_at": verification.created_at.isoformat(),
        "completed_at": verification.completed_at.isoformat() if verification.completed_at else None,
    }


def build_verification_evidence_pdf_bytes(payload: dict) -> bytes:
    subject = payload["verification_subject"]
    decision = payload.get("decision") or {}
    risk_assessment = payload.get("risk_assessment") or {}
    document_classification = payload.get("document_classification") or {}
    liveness = (payload.get("checks") or {}).get("liveness") or {}
    face_match = (payload.get("checks") or {}).get("face_match") or {}
    sections = [
        (
            "Verification Summary",
            [
                f"Verification ID: {payload['verification_id']}",
                f"Organization ID: {payload['organization_id']}",
                f"Tenant ID: {payload['tenant_id']}",
                f"External Reference: {payload.get('external_reference', '') or 'N/A'}",
                f"Status: {payload['status']}",
                f"Purpose: {payload.get('purpose', '') or 'N/A'}",
                f"Created At: {payload.get('created_at', '')}",
                f"Completed At: {payload.get('completed_at', '') or 'N/A'}",
            ],
        ),
        (
            "Verification Subject",
            [
                f"Subject ID: {subject.get('id', '')}",
                f"Full Name: {subject.get('full_name', '') or 'N/A'}",
                f"Email: {subject.get('email', '') or 'N/A'}",
                f"Phone Number: {subject.get('phone_number', '') or 'N/A'}",
            ],
        ),
        (
            "Decision and Risk",
            [
                f"Decision: {decision.get('decision', '') or 'N/A'}",
                f"Decision Type: {decision.get('decision_type', '') or 'N/A'}",
                f"Reason Code: {decision.get('reason_code', '') or 'N/A'}",
                f"Reason Detail: {decision.get('reason_detail', '') or 'N/A'}",
                f"Risk Level: {risk_assessment.get('risk_level', '') or 'N/A'}",
                f"Risk Score: {risk_assessment.get('risk_score', '') or 'N/A'}",
                f"Recommendation: {risk_assessment.get('recommendation', '') or 'N/A'}",
            ],
        ),
        (
            "Biometric Checks",
            [
                f"Liveness Status: {liveness.get('status', '') or 'N/A'}",
                f"Liveness Score: {liveness.get('score', '') or 'N/A'}",
                f"Liveness Confidence: {liveness.get('confidence_level', '') or 'N/A'}",
                f"Face Match Status: {face_match.get('status', '') or 'N/A'}",
                f"Face Match Score: {face_match.get('match_score', '') or 'N/A'}",
                f"Face Match Confidence: {face_match.get('confidence_level', '') or 'N/A'}",
            ],
        ),
        (
            "Identity Documents",
            [
                (
                    f"{item.get('document_type', '') or 'unknown'} "
                    f"({item.get('country_code', '') or 'N/A'}) "
                    f"status={item.get('status', '') or 'N/A'}"
                )
                for item in payload.get("identity_documents", [])
            ]
            or ["No identity documents recorded."],
        ),
        (
            "Document Classification",
            [
                f"Classification Status: {document_classification.get('classification_status', '') or 'N/A'}",
                f"Predicted Type: {document_classification.get('predicted_document_type', '') or 'N/A'}",
                f"Expected Type: {document_classification.get('expected_document_type', '') or 'N/A'}",
                f"Matched Expected Type: {document_classification.get('matched_expected_document_type', '')}",
                f"Workflow Action: {document_classification.get('workflow_action', '') or 'N/A'}",
                f"Requires Manual Review: {document_classification.get('requires_manual_review', '')}",
                f"Manual Review Priority: {(document_classification.get('manual_review') or {}).get('priority', '') or 'N/A'}",
                (
                    "Manual Review Reasons: "
                    + ", ".join((document_classification.get("manual_review") or {}).get("reason_codes") or [])
                    if (document_classification.get("manual_review") or {}).get("reason_codes")
                    else "Manual Review Reasons: N/A"
                ),
            ],
        ),
    ]
    return render_report_pdf(
        title="IdentityCore Verification Report",
        subtitle=f"Organization {payload['organization_id']}   Verification {payload['verification_id']}",
        sections=sections,
    )


def should_encrypt_evidence_objects() -> bool:
    return bool(getattr(settings, "APP_MANAGED_MEDIA_ENCRYPTION_ENABLED", True))


def download_verification_evidence_object(
    verification: Verification, *, pdf: bool = False
) -> tuple[bytes, str, str]:
    bucket_name = get_object_storage_evidence_bucket_name()
    storage_key = (
        (verification.metadata_json or {}).get("evidence_report_pdf_storage_key", "")
        if pdf
        else (verification.metadata_json or {}).get("evidence_report_storage_key", "")
    )
    encrypted = (
        (verification.metadata_json or {}).get("evidence_report_pdf_encrypted", False)
        if pdf
        else (verification.metadata_json or {}).get("evidence_report_encrypted", False)
    )
    filename = (
        f"{verification.public_id}-verification-report.pdf"
        if pdf
        else f"{verification.public_id}-verification-report.json"
    )
    if not bucket_name or not storage_key:
        raise ValueError("Evidence report object is not available.")
    content, content_type = get_object_bytes(
        bucket_name=bucket_name,
        key=storage_key,
        decrypt=encrypted,
        encryption_purpose=EVIDENCE_OBJECT_ENCRYPTION_PURPOSE,
    )
    return content, content_type, filename


def ensure_verification_evidence_report(verification: Verification) -> str | None:
    if verification.status not in TERMINAL_EVIDENCE_STATUSES:
        return None
    bucket_name = get_object_storage_evidence_bucket_name()
    if not bucket_name:
        return None

    storage_key = build_verification_evidence_storage_key(verification)
    pdf_storage_key = build_verification_evidence_pdf_storage_key(verification)
    payload = serialize_verification_evidence_report(verification)
    put_object_bytes(
        bucket_name=bucket_name,
        key=storage_key,
        content=json.dumps(payload, indent=2, sort_keys=True).encode("utf-8"),
        content_type="application/json",
        encrypt=should_encrypt_evidence_objects(),
        encryption_purpose=EVIDENCE_OBJECT_ENCRYPTION_PURPOSE,
    )
    put_object_bytes(
        bucket_name=bucket_name,
        key=pdf_storage_key,
        content=build_verification_evidence_pdf_bytes(payload),
        content_type="application/pdf",
        encrypt=should_encrypt_evidence_objects(),
        encryption_purpose=EVIDENCE_OBJECT_ENCRYPTION_PURPOSE,
    )
    metadata_json = dict(verification.metadata_json or {})
    metadata_json["evidence_report_storage_key"] = storage_key
    metadata_json["evidence_report_pdf_storage_key"] = pdf_storage_key
    metadata_json["evidence_report_encrypted"] = should_encrypt_evidence_objects()
    metadata_json["evidence_report_pdf_encrypted"] = should_encrypt_evidence_objects()
    verification.metadata_json = metadata_json
    verification.save(update_fields=["metadata_json", "updated_at"])
    return storage_key
