from common.public_api import public_api_path

from apps.verifications.views import (
    ManualReviewDecisionView,
    ManualReviewApprovalView,
    ManualReviewListView,
    VerificationCancelView,
    VerificationDetailView,
    VerificationEvidenceReportDownloadView,
    VerificationEvidenceReportPDFDownloadView,
    VerificationEvidenceReportView,
    VerificationListCreateView,
    VerificationResendLinkView,
    VerificationResultView,
)


urlpatterns = [
    public_api_path(
        "manual-reviews",
        ManualReviewListView.as_view(),
        methods=("GET",),
        name="manual-review-list",
    ),
    public_api_path(
        "manual-reviews/<str:verification_id>/decision",
        ManualReviewDecisionView.as_view(),
        methods=("POST",),
        name="manual-review-decision",
    ),
    public_api_path(
        "manual-reviews/<str:verification_id>/approval",
        ManualReviewApprovalView.as_view(),
        methods=("POST",),
        name="manual-review-approval",
    ),
    public_api_path(
        "",
        VerificationListCreateView.as_view(),
        methods=("GET", "POST"),
        name="verification-list-create",
    ),
    public_api_path(
        "<str:verification_id>",
        VerificationDetailView.as_view(),
        methods=("GET",),
        name="verification-detail",
    ),
    public_api_path(
        "<str:verification_id>/result",
        VerificationResultView.as_view(),
        methods=("GET",),
        name="verification-result",
    ),
    public_api_path(
        "<str:verification_id>/evidence-report",
        VerificationEvidenceReportView.as_view(),
        methods=("GET",),
        name="verification-evidence-report",
    ),
    public_api_path(
        "<str:verification_id>/evidence-report/download",
        VerificationEvidenceReportDownloadView.as_view(),
        methods=("GET",),
        name="verification-evidence-report-download",
    ),
    public_api_path(
        "<str:verification_id>/evidence-report/download.pdf",
        VerificationEvidenceReportPDFDownloadView.as_view(),
        methods=("GET",),
        name="verification-evidence-report-pdf-download",
    ),
    public_api_path(
        "<str:verification_id>/cancel",
        VerificationCancelView.as_view(),
        methods=("POST",),
        name="verification-cancel",
    ),
    public_api_path(
        "<str:verification_id>/resend-link",
        VerificationResendLinkView.as_view(),
        methods=("POST",),
        name="verification-resend-link",
    ),
]
