# Generated by Django 6.0.6 on 2026-07-12 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("government_id", "Government ID"),
                            ("banking_kyc", "Banking KYC"),
                            ("employment", "Employment"),
                            ("education", "Education"),
                            ("healthcare", "Healthcare"),
                            ("age_verification", "Age Verification"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("countries_json", models.JSONField(blank=True, default=list)),
                ("required_checks_json", models.JSONField(blank=True, default=list)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("cloned_by_organizations", models.PositiveIntegerField(default=0)),
                ("owner_team", models.CharField(blank=True, max_length=120)),
                ("risk_level", models.CharField(blank=True, max_length=32)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
