export const statusBadgeVariants = {
  approved: "success",
  verified: "success",
  active: "success",
  review: "warning",
  pending: "secondary",
  rejected: "destructive",
  revoked: "secondary",
  expired: "outline",
  invited: "secondary",
  draft: "outline",
} as const;

export function getStatusBadgeVariant(status: string) {
  return statusBadgeVariants[status as keyof typeof statusBadgeVariants] ?? "outline";
}

export const verificationRequests = [
  {
    id: "REQ-1091",
    subjectId: "sub-001",
    subject: "James Okafor",
    email: "j.okafor@example.com",
    policy: "Standard KYC",
    policyId: "pol-standard-kyc",
    status: "approved",
    created: "Jul 6, 2026",
    expires: "Jul 13, 2026",
    link: "https://verify.identitycore.com/verify/sess_1091",
    decision: "Approved automatically after document and selfie match.",
  },
  {
    id: "REQ-1090",
    subjectId: "sub-002",
    subject: "Amara Diallo",
    email: "amara.d@sample.io",
    policy: "Enhanced KYC",
    policyId: "pol-enhanced-kyc",
    status: "review",
    created: "Jul 6, 2026",
    expires: "Jul 13, 2026",
    link: "https://verify.identitycore.com/verify/sess_1090",
    decision: "Queued for manual review because liveness confidence was below threshold.",
  },
  {
    id: "REQ-1089",
    subjectId: "sub-003",
    subject: "Lena Muller",
    email: "l.mueller@corp.de",
    policy: "Standard KYC",
    policyId: "pol-standard-kyc",
    status: "approved",
    created: "Jul 5, 2026",
    expires: "Jul 12, 2026",
    link: "https://verify.identitycore.com/verify/sess_1089",
    decision: "Approved after all checks passed.",
  },
  {
    id: "REQ-1088",
    subjectId: "sub-004",
    subject: "Kevin Santos",
    email: "kevin.s@testco.com",
    policy: "Standard KYC",
    policyId: "pol-standard-kyc",
    status: "rejected",
    created: "Jul 5, 2026",
    expires: "Jul 12, 2026",
    link: "https://verify.identitycore.com/verify/sess_1088",
    decision: "Rejected because face match confidence fell below minimum threshold.",
  },
  {
    id: "REQ-1087",
    subjectId: "sub-005",
    subject: "Priya Nair",
    email: "priya.n@example.in",
    policy: "Lite KYC",
    policyId: "pol-lite-kyc",
    status: "pending",
    created: "Jul 5, 2026",
    expires: "Jul 12, 2026",
    link: "https://verify.identitycore.com/verify/sess_1087",
    decision: "Waiting for the subject to complete the session.",
  },
  {
    id: "REQ-1084",
    subjectId: "sub-006",
    subject: "Marcus Bello",
    email: "m.bello@ng.co",
    policy: "Standard KYC",
    policyId: "pol-standard-kyc",
    status: "expired",
    created: "Jun 29, 2026",
    expires: "Jul 6, 2026",
    link: "https://verify.identitycore.com/verify/sess_1084",
    decision: "Link expired before the subject finished document capture.",
  },
];

export const verificationSubjects = [
  {
    id: "sub-001",
    name: "James Okafor",
    email: "j.okafor@example.com",
    verifications: 2,
    lastVerified: "2026-07-06",
    status: "verified",
    country: "Ghana",
    notes: "Low-friction repeat customer with consistent document history.",
  },
  {
    id: "sub-002",
    name: "Amara Diallo",
    email: "amara.d@sample.io",
    verifications: 1,
    lastVerified: "2026-07-06",
    status: "review",
    country: "Senegal",
    notes: "Waiting on compliance reviewer due to edge-case liveness signal.",
  },
  {
    id: "sub-003",
    name: "Lena Muller",
    email: "l.mueller@corp.de",
    verifications: 3,
    lastVerified: "2026-07-05",
    status: "verified",
    country: "Germany",
    notes: "All recent checks approved automatically.",
  },
  {
    id: "sub-004",
    name: "Kevin Santos",
    email: "kevin.s@testco.com",
    verifications: 1,
    lastVerified: "2026-07-05",
    status: "rejected",
    country: "Brazil",
    notes: "Submission failed face comparison and requires escalation review.",
  },
  {
    id: "sub-005",
    name: "Priya Nair",
    email: "priya.n@example.in",
    verifications: 1,
    lastVerified: "2026-07-05",
    status: "pending",
    country: "India",
    notes: "Verification link has been sent but not finished.",
  },
];

export const verificationPolicies = [
  {
    id: "pol-standard-kyc",
    name: "Standard KYC",
    description: "Government ID + selfie with face match.",
    docTypes: ["Passport", "National ID", "Driver's License"],
    selfie: true,
    liveness: false,
    active: true,
    usageCount: 8420,
    expiryDays: 7,
    faceMatchThreshold: 80,
    manualReviewThreshold: 70,
    retentionDays: 365,
  },
  {
    id: "pol-enhanced-kyc",
    name: "Enhanced KYC",
    description: "Passport only with selfie and liveness check.",
    docTypes: ["Passport"],
    selfie: true,
    liveness: true,
    active: true,
    usageCount: 3211,
    expiryDays: 7,
    faceMatchThreshold: 90,
    manualReviewThreshold: 80,
    retentionDays: 365,
  },
  {
    id: "pol-lite-kyc",
    name: "Lite KYC",
    description: "Any government ID, no selfie required.",
    docTypes: ["Passport", "National ID", "Driver's License"],
    selfie: false,
    liveness: false,
    active: false,
    usageCount: 1216,
    expiryDays: 14,
    faceMatchThreshold: null,
    manualReviewThreshold: 60,
    retentionDays: 180,
  },
];

export const apiKeys = [
  {
    id: "key-001",
    name: "Production Key",
    prefix: "ic_live_sk_",
    suffix: "...9xKq",
    created: "May 1, 2026",
    lastUsed: "Jul 6, 2026",
    status: "active",
    scopes: ["verifications:write", "verifications:read", "webhooks:read"],
    environment: "Production",
  },
  {
    id: "key-002",
    name: "Staging Key",
    prefix: "ic_test_sk_",
    suffix: "...4mPw",
    created: "Apr 14, 2026",
    lastUsed: "Jul 5, 2026",
    status: "active",
    scopes: ["verifications:write", "verifications:read"],
    environment: "Staging",
  },
  {
    id: "key-004",
    name: "Old Dev Key",
    prefix: "ic_test_sk_",
    suffix: "...2bHs",
    created: "Jan 10, 2026",
    lastUsed: "Feb 15, 2026",
    status: "revoked",
    scopes: ["verifications:read"],
    environment: "Development",
  },
];

export const webhooks = [
  {
    id: "wh-001",
    url: "https://api.acmecorp.com/hooks/identity",
    events: ["verification.approved", "verification.rejected", "verification.review"],
    status: "active",
    lastDelivery: "2026-07-06 22:15",
    successRate: "99.2%",
    secretRotation: "May 2026",
  },
  {
    id: "wh-002",
    url: "https://hooks.acmecorp.com/compliance",
    events: ["verification.approved"],
    status: "active",
    lastDelivery: "2026-07-06 22:11",
    successRate: "100%",
    secretRotation: "Apr 2026",
  },
  {
    id: "wh-003",
    url: "https://old-system.acmecorp.com/notify",
    events: ["verification.approved", "verification.rejected"],
    status: "failing",
    lastDelivery: "2026-07-04 08:22",
    successRate: "12.5%",
    secretRotation: "Jan 2026",
  },
];

export const projects = [
  {
    id: "proj-core-onboarding",
    name: "Core onboarding",
    environment: "Production",
    policies: 3,
    apiKeys: 2,
    webhooks: 2,
    status: "active",
    description: "Primary onboarding journey used by customer success and ops teams.",
  },
  {
    id: "proj-sandbox-labs",
    name: "Sandbox labs",
    environment: "Sandbox",
    policies: 2,
    apiKeys: 1,
    webhooks: 1,
    status: "active",
    description: "Used by engineering for test integrations and webhook simulations.",
  },
  {
    id: "proj-partner-pilot",
    name: "Partner pilot",
    environment: "Pilot",
    policies: 1,
    apiKeys: 1,
    webhooks: 0,
    status: "draft",
    description: "Pilot workspace for a regulated partner onboarding rollout.",
  },
];
