# Generated by Django 6.0.6 on 2026-07-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="public_id",
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
