# Generated by Django 6.0.6 on 2026-07-04 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tenants', '0001_initial'),
        ('verification_subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('policy_public_id', models.CharField(blank=True, max_length=64)),
                ('policy_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending_consent', 'Pending Consent'), ('in_progress', 'In Progress'), ('awaiting_document', 'Awaiting Document'), ('awaiting_selfie', 'Awaiting Selfie'), ('processing', 'Processing'), ('manual_review_required', 'Manual Review Required'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending_consent', max_length=32)),
                ('purpose', models.CharField(max_length=255)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('redirect_url', models.URLField(blank=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_verifications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='organizations.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='tenants.tenant')),
                ('verification_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='verification_subjects.verificationsubject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('session_token_hash', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='created', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_sessions', to='tenants.tenant')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='verifications.verification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
