# Generated by Django 6.0.6 on 2026-07-06 16:44

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verifications", "0002_verificationdecision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verification",
            name="metadata_json",
            field=common.fields.EncryptedJSONField(
                blank=True, default=dict, encryption_purpose="verifications.metadata"
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="policy_snapshot_json",
            field=common.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                encryption_purpose="verifications.policy_snapshot",
            ),
        ),
        migrations.AlterField(
            model_name="verificationdecision",
            name="evidence_summary_json",
            field=common.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                encryption_purpose="verifications.decision.evidence_summary",
            ),
        ),
    ]
