# Generated by Django 6.0.6 on 2026-08-03 08:08

from django.db import migrations, models


SESSION_ACTIONS = [
    "session:read",
    "consent:accept",
    "document:capture",
    "selfie:capture",
    "liveness:challenge",
    "liveness:submit",
    "upload:create",
    "upload:transfer",
    "mobile_handoff:create",
]


def populate_allowed_actions(apps, schema_editor):
    VerificationSession = apps.get_model("verifications", "VerificationSession")
    VerificationSession.objects.filter(allowed_actions_json=[]).update(
        allowed_actions_json=SESSION_ACTIONS
    )


class Migration(migrations.Migration):

    dependencies = [
        ("verifications", "0008_verification_verif_tenant_created_pk_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationsession",
            name="allowed_actions_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_allowed_actions, migrations.RunPython.noop),
    ]
