# Generated by Django 6.0.6 on 2026-08-03 08:12

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verifications", "0009_verificationsession_allowed_actions_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="workflow_snapshot_json",
            field=common.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                encryption_purpose="verifications.workflow_snapshot",
            ),
        ),
    ]
