# Generated by Django 6.0.6 on 2026-08-03 08:37

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifications", "0010_verification_workflow_snapshot_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationdecision",
            name="contract_version",
            field=models.CharField(default="1", max_length=16),
        ),
        migrations.AddField(
            model_name="verificationdecision",
            name="input_snapshot_json",
            field=common.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                encryption_purpose="verifications.decision.input_snapshot",
            ),
        ),
        migrations.AddField(
            model_name="verificationdecision",
            name="reason_codes_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
