# Generated by Django 6.0.8 on 2026-08-12 14:14

from django.db import migrations, models


def backfill_proposed_decisions(apps, schema_editor):
    VerificationDecision = apps.get_model("verifications", "VerificationDecision")
    for decision in VerificationDecision.objects.only("pk", "decision").iterator():
        decision.proposed_decision = decision.decision
        decision.save(update_fields=["proposed_decision"])


class Migration(migrations.Migration):

    dependencies = [
        ("verifications", "0015_processingjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationdecision",
            name="proposed_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "Created"),
                    ("pending_consent", "Pending Consent"),
                    ("in_progress", "In Progress"),
                    ("awaiting_document", "Awaiting Document"),
                    ("awaiting_selfie", "Awaiting Selfie"),
                    ("processing", "Processing"),
                    ("manual_review_required", "Manual Review Required"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(backfill_proposed_decisions, migrations.RunPython.noop),
    ]
