"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Button, Card, CardContent, CardHeader, CardTitle, Input, Label } from "@identitycore/ui";
import { dashboardApi, Policy, VerificationSummary } from "@/lib/dashboard-api";
export function LiveVerificationsPage() {
  const [items, setItems] = useState<VerificationSummary[]>([]); const [policies, setPolicies] = useState<Policy[]>([]); const [link, setLink] = useState(""); const [error, setError] = useState("");
  const load = () => Promise.all([dashboardApi.verifications(), dashboardApi.policies()]).then(([page, templates]) => { setItems(page.results); setPolicies(templates.filter(item => item.status === "active")); }).catch(() => setError("Verification requests could not be loaded.")); useEffect(() => { void load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const result = await dashboardApi.createVerification({ purpose: data.get("purpose"), policy_id: data.get("policy_id"), external_reference: data.get("external_reference"), verification_subject: { full_name: data.get("full_name"), email: data.get("email") } }); setLink(result.verification_url); event.currentTarget.reset(); await load(); } catch { setError("The request could not be created. Choose an active template and check the subject details."); } }
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Verification requests</h1><p className="text-slate-600">Create and track hosted identity checks.</p></div>{error ? <p className="text-red-600">{error}</p> : null}{link ? <Card><CardContent className="flex items-center gap-3 p-4"><Input readOnly value={link} /><Button onClick={() => navigator.clipboard.writeText(link)}>Copy link</Button></CardContent></Card> : null}<Card><CardHeader><CardTitle>Create request</CardTitle></CardHeader><CardContent><form onSubmit={create} className="grid gap-3 md:grid-cols-2"><div><Label>Full name</Label><Input name="full_name" required /></div><div><Label>Email</Label><Input name="email" type="email" required /></div><div><Label>Purpose</Label><Input name="purpose" required /></div><div><Label>External reference</Label><Input name="external_reference" /></div><select name="policy_id" required className="h-10 rounded-md border bg-white px-3"><option value="">Choose template</option>{policies.map(item => <option key={item.id} value={item.id}>{item.name} v{item.version}</option>)}</select><Button>Create and email link</Button></form></CardContent></Card><div className="grid gap-3">{items.map(item => <Link key={item.id} href={`/verifications/${item.id}`} className="rounded-2xl border bg-white p-4"><span className="font-medium">{item.subject.full_name || item.subject.email}</span><span className="ml-3 text-sm text-slate-500">{item.policy.name} · {item.status}</span></Link>)}</div></div>;
}
