# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("pending", "Pending"),
                    ("pending_review", "Pending review"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="pending_review",
                max_length=32,
            ),
        ),
    ]
