# Generated by Django 6.0.6 on 2026-07-04 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('client_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('client_secret_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('rotating', 'Rotating'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=32)),
                ('scopes_json', models.JSONField(blank=True, default=list)),
                ('allowed_ips_json', models.JSONField(blank=True, default=list)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_api_clients', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_clients', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
