# Generated by Django 6.0.6 on 2026-07-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_clients", "0003_api_idempotency_record"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apiidempotencyrecord",
            new_name="api_clients_api_cli_ca6b6b_idx",
            old_name="api_clients_api_cli_8b5b2e_idx",
        ),
    ]
