# Generated by Django 6.0.6 on 2026-08-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_clients",
            "0004_rename_api_clients_api_cli_8b5b2e_idx_api_clients_api_cli_ca6b6b_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apiclient",
            name="previous_client_secret_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apiclient",
            name="previous_client_secret_hash",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
