# Generated by Django 6.0.8 on 2026-08-22 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_clients", "0006_idempotency_principals"),
        ("tenants", "0003_alter_tenant_settings_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="apiidempotencyrecord",
            name="unique_api_client_idempotency_key",
        ),
        migrations.AddIndex(
            model_name="apiidempotencyrecord",
            index=models.Index(
                fields=["tenant", "created_at"], name="api_clients_tenant__4f03a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiidempotencyrecord",
            index=models.Index(
                fields=["user", "created_at"], name="api_clients_user_id_870aee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="apiidempotencyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("api_client__isnull", False), ("user__isnull", True)),
                    models.Q(("api_client__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="idempotency_record_has_one_principal",
            ),
        ),
        migrations.AddConstraint(
            model_name="apiidempotencyrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("api_client__isnull", False)),
                fields=("tenant", "api_client", "key"),
                name="unique_api_client_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="apiidempotencyrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("tenant", "user", "key"),
                name="unique_user_idempotency_key",
            ),
        ),
    ]
