# Generated by Django 6.0.6 on 2026-07-12 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0004_organizationsupportingdocument"),
        ("tenants", "0003_alter_tenant_settings_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("due_soon", "Due soon"),
                            ("overdue", "Overdue"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("monthly_recurring_revenue", models.CharField(max_length=64)),
                ("monthly_check_count", models.PositiveIntegerField(default=0)),
                ("current_invoice", models.CharField(blank=True, max_length=64)),
                ("plan", models.CharField(blank=True, max_length=64)),
                ("billing_cycle", models.CharField(default="monthly", max_length=32)),
                ("owner_team", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_records",
                        to="organizations.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
