# Generated by Django 6.0.6 on 2026-07-04 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('verification_subjects', '0001_initial'),
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('document_type_id', models.CharField(db_index=True, max_length=64)),
                ('country_profile_id', models.CharField(blank=True, max_length=64)),
                ('local_document_name', models.CharField(blank=True, max_length=255)),
                ('document_number_hash', models.CharField(blank=True, db_index=True, max_length=255)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=32)),
                ('extracted_data_json', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_documents', to='tenants.tenant')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_documents', to='verifications.verification')),
                ('verification_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_documents', to='verification_subjects.verificationsubject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
