# Generated by Django 6.0.6 on 2026-07-06 16:45

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity_documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identitydocument",
            name="extracted_data_json",
            field=common.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                encryption_purpose="identity_documents.extracted_data",
            ),
        ),
    ]
