# Generated by Django 6.0.6 on 2026-07-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity_documents", "0002_alter_identitydocument_extracted_data_json"),
        ("identity_documents", "0002_identitydocument_manual_review_status"),
    ]

    operations = []
