# Generated by Django 6.0.6 on 2026-07-06 16:44

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verification_subjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationsubject",
            name="metadata_json",
            field=common.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                encryption_purpose="verification_subjects.metadata",
            ),
        ),
    ]
