# Generated by Django 6.0.6 on 2026-08-03 09:07

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_tenant_settings_json"),
        ("verification_subjects", "0002_alter_verificationsubject_metadata_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationSubjectExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "payload_json",
                    common.fields.EncryptedJSONField(
                        default=dict,
                        encryption_purpose="verification_subjects.export_payload",
                    ),
                ),
                ("download_token_hash", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exports",
                        to="verification_subjects.verificationsubject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_exports",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
