# Generated by Django 6.0.6 on 2026-07-05 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biometrics", "0002_livenesscheck"),
        ("document_captures", "0002_initial"),
        ("identity_documents", "0001_initial"),
        ("tenants", "0001_initial"),
        ("verifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("provider_check_id", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("not_matched", "Not Matched"),
                            ("inconclusive", "Inconclusive"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="inconclusive",
                        max_length=32,
                    ),
                ),
                (
                    "match_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("confidence_level", models.CharField(blank=True, max_length=32)),
                (
                    "threshold_used",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("model_version", models.CharField(blank=True, max_length=64)),
                ("matched_at", models.DateTimeField(db_index=True)),
                (
                    "document_capture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_matches",
                        to="document_captures.documentcapture",
                    ),
                ),
                (
                    "identity_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_matches",
                        to="identity_documents.identitydocument",
                    ),
                ),
                (
                    "selfie_capture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_matches",
                        to="biometrics.selfiecapture",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_matches",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_matches",
                        to="verifications.verification",
                    ),
                ),
            ],
            options={
                "ordering": ["-matched_at"],
            },
        ),
    ]
