# Generated by Django 6.0.6 on 2026-07-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biometrics", "0003_facematch"),
        ("tenants", "0001_initial"),
        ("verifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivenessChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("public_id", models.CharField(editable=False, max_length=64, unique=True)),
                ("actions", models.JSONField(default=list)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="liveness_challenges", to="tenants.tenant")),
                ("verification", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="liveness_challenges", to="verifications.verification")),
                ("verification_session", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="liveness_challenges", to="verifications.verificationsession")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="livenesscheck",
            name="challenge",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="liveness_checks", to="biometrics.livenesschallenge"),
        ),
    ]
