from common.public_api import public_api_path

from apps.verification_sessions.views import (
    VerificationSessionConsentView,
    VerificationSessionDetailView,
    VerificationSessionDocumentView,
    VerificationSessionLivenessView,
    VerificationSessionLivenessChallengeView,
    VerificationSessionSelfieView,
    VerificationSessionStatusView,
    VerificationMobileHandoffCreateView,
    VerificationMobileHandoffRedeemView,
)


urlpatterns = [
    public_api_path(
        "mobile-handoff/redeem",
        VerificationMobileHandoffRedeemView.as_view(),
        methods=("POST",),
        name="verification-mobile-handoff-redeem",
    ),
    public_api_path(
        "<str:session_id>",
        VerificationSessionDetailView.as_view(),
        methods=("GET",),
        name="verification-session-detail",
    ),
    public_api_path(
        "<str:session_id>/consent",
        VerificationSessionConsentView.as_view(),
        methods=("POST",),
        name="verification-session-consent",
    ),
    public_api_path(
        "<str:session_id>/documents",
        VerificationSessionDocumentView.as_view(),
        methods=("POST",),
        name="verification-session-documents",
    ),
    public_api_path(
        "<str:session_id>/selfies",
        VerificationSessionSelfieView.as_view(),
        methods=("POST",),
        name="verification-session-selfies",
    ),
    public_api_path(
        "<str:session_id>/liveness",
        VerificationSessionLivenessView.as_view(),
        methods=("POST",),
        name="verification-session-liveness",
    ),
    public_api_path(
        "<str:session_id>/liveness/challenge",
        VerificationSessionLivenessChallengeView.as_view(),
        methods=("POST",),
        name="verification-session-liveness-challenge",
    ),
    public_api_path(
        "<str:session_id>/status",
        VerificationSessionStatusView.as_view(),
        methods=("GET",),
        name="verification-session-status",
    ),
    public_api_path(
        "<str:session_id>/mobile-handoff",
        VerificationMobileHandoffCreateView.as_view(),
        methods=("POST",),
        name="verification-mobile-handoff-create",
    ),
]
