# Generated by Django 6.0.6 on 2026-07-06 16:45

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskassessment",
            name="signals_json",
            field=common.fields.EncryptedJSONField(
                blank=True, default=dict, encryption_purpose="risk.signals"
            ),
        ),
    ]
