# Generated by Django 6.0.6 on 2026-07-05 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32)),
                ('required_document_types_json', models.JSONField(blank=True, default=list)),
                ('required_liveness_level', models.CharField(default='passive', max_length=32)),
                ('face_match_threshold', models.DecimalField(decimal_places=4, default=0.85, max_digits=5)),
                ('manual_review_threshold', models.DecimalField(decimal_places=4, default=0.65, max_digits=5)),
                ('verification_expiry_minutes', models.PositiveIntegerField(default=1440)),
                ('media_retention_days', models.PositiveIntegerField(default=30)),
                ('metadata_retention_days', models.PositiveIntegerField(default=365)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_verification_policies', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_policies', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name', '-version'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name', 'version'), name='verification_policy_tenant_name_version_uniq')],
            },
        ),
    ]
