# Generated by Django 6.0.8 on 2026-08-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification_policies", "0003_policy_consent_and_locales"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationpolicy",
            name="maker_checker_required",
            field=models.BooleanField(default=False),
        ),
    ]
