from .gh import DEFINITIONS as GH_DEFINITIONS
from .global_documents import DEFINITIONS as GLOBAL_DEFINITIONS
from .west_africa_candidates import DEFINITIONS as WEST_AFRICA_CANDIDATE_DEFINITIONS

__all__ = ["GH_DEFINITIONS", "GLOBAL_DEFINITIONS", "WEST_AFRICA_CANDIDATE_DEFINITIONS"]
