# Generated by Django 6.0.6 on 2026-07-06 16:44

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_add_pending_email_verification_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="settings_json",
            field=common.fields.EncryptedJSONField(
                blank=True, default=dict, encryption_purpose="organizations.settings"
            ),
        ),
    ]
