# Generated by Django 6.0.6 on 2026-07-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='signing_key',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
